import std/os
import fileWriter

proc batchPre*(filename: string) =
    when defined(windows):
        writeIR("@echo off\nREM Batch file generated by Quill Compiler\n",
                splitFile(filename).name & ".bat")
    else:
        writeIR("#!/bin/bash\n# Batch file generated by Quill Compiler\n",
                splitFile(filename).name & ".bat")