import std/os
import fileWriter

proc batchPre*(filename: string) =
    let file = splitFile(filename).name & ".bat"
    
    when defined(windows):
        writeCode("@echo off\n", file)
        # Adds Comment to show Auto Generated
        writeCode("REM Batch file generated by Quill Compiler\n", file)
    else:
        writeCode("#!/bin/bash\n", file)
        # Adds Comment to show Auto Generated
        writeCode("# Batch file generated by Quill Compiler\n", file)