import std/os
import fileWriter
import tables

proc llvmPre*(filename: string) =
    writeIR("; LLVM IR generated by Quill Compiler",
            splitFile(filename).name & ".ll")

proc llvmPost*(filename: string, vars: Table[string, (string, string, int)], funcCalls: seq[string]) =
    # Now write the _start function (custom entry point)
    writeIR("", splitFile(filename).name & ".ll")
    writeIR("define i32 @_start() {", splitFile(filename).name & ".ll")
    writeIR("entry:", splitFile(filename).name & ".ll")
        
    # Add variable allocations and stores from let statements
    for varName, (varType, value, strLen) in vars.pairs():
        if varType == "ptr":
            # For string variables (pointers to global constants)
            writeIR("  %" & varName & " = alloca ptr, align 8", splitFile(filename).name & ".ll")
            writeIR("  store ptr " & value & ", ptr %" & varName & ", align 8", splitFile(filename).name & ".ll")
        else:
            # For numeric types
            let alignment = case varType
                of "i32", "float": "4"
                of "i64", "double": "8"
                of "i1": "1"
                else: "4"
                
            writeIR("  %" & varName & " = alloca " & varType & ", align " & alignment, splitFile(filename).name & ".ll")
            writeIR("  store " & varType & " " & value & ", ptr %" & varName & ", align " & alignment, splitFile(filename).name & ".ll")
        
    # Add all the function calls
    for call in funcCalls:
        writeIR(call, splitFile(filename).name & ".ll")
        
    # Exit syscall for smallest binary (no libc exit)
    when defined(windows):
        writeIR("  ret i32 0", splitFile(filename).name & ".ll")
    else:
        # Linux syscall exit(0) - smallest possible exit
        writeIR("  call void asm sideeffect \"movl $$60, %eax; xorl %edi, %edi; syscall\", \"~{dirflag},~{fpsr},~{flags}\"()", splitFile(filename).name & ".ll")
        writeIR("  unreachable", splitFile(filename).name & ".ll")
        
    writeIR("}", splitFile(filename).name & ".ll")