import std/os
import fileWriter

proc pythonPre*(filename: string) =
    let file = splitFile(filename).name & ".py"
    
    if fileExists(file):
        try:
            removeFile(file)
        except OSError as e:
            echo "Error deleting file: ", e.msg
    
    # Adds Comment to show Auto Generated
    writeCode("# Python file generated by Quill Compiler\n", file)