import std/os
import fileWriter

proc pythonPre*(filename: string) =
    let file = splitFile(filename).name & ".py"
    
    if fileExists(file):
        try:
            removeFile(file)
        except OSError as e:
            echo "Error deleting file: ", e.msg
    
    # Adds Comment to show Auto Generated
    writeCode("# Python file generated by Quill Compiler\n", file)

proc pythonPost*(filename: string, functionDefs: seq[string], entryCode: seq[string]) =
    let file = splitFile(filename).name & ".py"
    
    # Write all function definitions
    for funcDef in functionDefs:
        writeCode(funcDef, file)

    # Write all entry code
    for line in entryCode:
        writeCode(line, file)