import std/os
import fileWriter

proc rustPre*(filename: string) =
    let file = splitFile(filename).name & ".rs"
    
    if fileExists(file):
        try:
            removeFile(file)
        except OSError as e:
            echo "Error deleting file: ", e.msg
    
    # Adds Comment to show Auto Generated
    writeCode("// Rust file generated by Quill Compiler\n", file)
    writeCode("fn main() {", file)

proc rustPost*(filename: string) =
    writeCode("}", splitFile(filename).name & ".rs")