import std/os
import fileWriter

proc rustPre*(filename: string) =
    let file = splitFile(filename).name & ".rs"
    
    if fileExists(file):
        try:
            removeFile(file)
        except OSError as e:
            echo "Error deleting file: ", e.msg

proc rustPost*(filename: string, globalDecls: seq[string], functionDefs: seq[string], entryCode: seq[string]) =
    let file = splitFile(filename).name & ".rs"
    
    # Cargo eval statements must be first at all times
    for globalDecl in globalDecls:
        writeCode(globalDecl, file)

    # Adds Comment to show Auto Generated
    writeCode("// Rust file generated by Quill Compiler\n", file)

    # Write all function definitions
    for funcDef in functionDefs:
        writeCode(funcDef, file)
    
    writeCode("fn main() {", file)

    # Write all entry code
    for line in entryCode:
        writeCode(line, file)
    
    # Close main function
    writeCode("}", file)